name: Test Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  pre-build-documentation:
    uses: TLW-orgtesting/ci-config/.github/workflows/test_docs_tmpl.yaml@main
    
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Obtain Source
      uses: actions/checkout@v2
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      run: .github/workflows/scripts/build_docs.sh parallelzone_cxx_api
