name: Test Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  pre-build-documentation:
    uses: TLW-orgtesting/ci-config/.github/workflows/test_docs_tmpl.yaml@main
    
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
    steps:
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      run: .github/workflows/scripts/build_docs.sh parallelzone_cxx_api
