name: Test Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:    
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: TLW-orgtesting/ci-config/.github/workflows/test_docs_tmpl.yaml@main
      - name: Build documentation
      - run: .github/workflows/scripts/build_docs.sh parallelzone_cxx_api
